Mar 09 12:36:24 ip-172-31-43-157 systemd[1]: Started Telegram Bot Service.
Mar 09 12:37:35 ip-172-31-43-157 python[47980]: name 'callback_query' is not defined
Mar 09 12:37:35 ip-172-31-43-157 python[47980]: Traceback (most recent call last):
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/events.py", line 111, in download_playlist
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:     await app.forward_messages(chat_id=callback_query.message.chat.id, from_chat_id=CHANNEL_ID, message_ids=int(str(matching_records.first().id)))
Mar 09 12:37:35 ip-172-31-43-157 python[47980]: NameError: name 'callback_query' is not defined
Mar 09 12:37:35 ip-172-31-43-157 python[47980]: During handling of the above exception, another exception occurred:
Mar 09 12:37:35 ip-172-31-43-157 python[47980]: Traceback (most recent call last):
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:     await handler.callback(self.client, *args)
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/main.py", line 203, in handle_callback_query
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:     await event_controller(client, callback_query, app)
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/events.py", line 361, in event_controller
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:     await asyncio.create_task(download_playlist(callback_data, app, user_language, downloading, chat_id, client))
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/events.py", line 172, in download_playlist
Mar 09 12:37:35 ip-172-31-43-157 python[47980]:     await client.send_message(chat_id=callback_query.message.chat.id, text=user_language['err_playlist_download'])
Mar 09 12:37:35 ip-172-31-43-157 python[47980]: NameError: name 'callback_query' is not defined
Mar 09 12:37:56 ip-172-31-43-157 python[47980]: name 'callback_query' is not defined
Mar 09 12:37:56 ip-172-31-43-157 python[47980]: Traceback (most recent call last):
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/events.py", line 136, in download_playlist
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:     chat_id=callback_query.message.chat.id
Mar 09 12:37:56 ip-172-31-43-157 python[47980]: NameError: name 'callback_query' is not defined
Mar 09 12:37:56 ip-172-31-43-157 python[47980]: During handling of the above exception, another exception occurred:
Mar 09 12:37:56 ip-172-31-43-157 python[47980]: Traceback (most recent call last):
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:     await handler.callback(self.client, *args)
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/main.py", line 203, in handle_callback_query
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:     await event_controller(client, callback_query, app)
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/events.py", line 361, in event_controller
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:     await asyncio.create_task(download_playlist(callback_data, app, user_language, downloading, chat_id, client))
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:   File "/home/ubuntu/breaktube/events.py", line 172, in download_playlist
Mar 09 12:37:56 ip-172-31-43-157 python[47980]:     await client.send_message(chat_id=callback_query.message.chat.id, text=user_language['err_playlist_download'])
Mar 09 12:37:56 ip-172-31-43-157 python[47980]: NameError: name 'callback_query' is not defined
